# Generated by Django 3.0.4 on 2020-03-22 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_bag_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile'),
        ),
    ]
