# Generated by Django 3.0.4 on 2020-03-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_bag_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
