# Generated by Django 3.0.4 on 2020-03-21 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200321_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='bag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Bag'),
            preserve_default=False,
        ),
    ]
